### ISSUE TITLE
Look into using S2VXTestScene's scheduler instead of making our own clock for tests

### ISSUE THREAD

**Issue by maxrchung** [maxrchung/S2VX#398]
As a developer, I want to use the test scene's scheduler instead of manipulating our own clock so that we can visually see changes in the test GUI.

**Comment by Xenocidel** [comment]
We can designate visual tests to be a Headless only test if we put `[HeadlessTest]` above the class
![image](https://user-images.githubusercontent.com/12549910/110418584-ae980400-804c-11eb-989f-b542581ea2e2.png)

**Comment by Xenocidel** [comment]
A little off-topic but I looked at how osu! does their visual tests for sliders (ref: `TestSceneSliderInput.cs`) and it looks like they utilize their replay system to compare frames with what they expect to happen. Pretty neat.

**Comment by Xenocidel** [comment]
Experimenting with using the built-in clock and scheduling actions rather than using our own clock. I observe these weird behaviors and I have no explanation as to why this is happening:
- ~~The scheduled action would repeat itself endlessly even though `repeat` is not set to true~~ This occurs if there is a press without a release
- The scheduled action would be way earlier than anticipated (ranging from 800-1000ms)
![image](https://user-images.githubusercontent.com/12549910/110430475-4f90ba00-8061-11eb-9c45-1f4da4db75c7.png)

**Comment by Xenocidel** [comment]
I have found the discrepancy. The `Time.Current` used in `AddNote` is Story's Time, which is NOT the same as the TestScene's Time.
![image](https://user-images.githubusercontent.com/12549910/110432826-83211380-8064-11eb-959b-d0791ab8ce8e.png)

Changing the latter to `Story.Time.Current` fixes this. However, due to the nature of Update(), there will be some error.
![image](https://user-images.githubusercontent.com/12549910/110432963-b5cb0c00-8064-11eb-9d96-30ee5f2cf563.png)

**Comment by Xenocidel** [comment]
osu! does not do real-time testing because of the imprecision of `Update()` but rather the replay frame state comparison as mentioned previously.

I'm satisfied with the results and propose we move forward with the way we are doing it now with our own clock + adding [HeadlessTest] to tests which are not actually testing anything Visual.
